"""crear tablas bien

Revision ID: d806efa533b1
Revises: 
Create Date: 2025-06-03 18:10:17.496492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd806efa533b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo_area', sa.String(length=50), nullable=False),
    sa.Column('responsable', sa.String(length=150), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_estimacion', sa.DateTime(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('retroalimentacion', sa.Text(), nullable=True),
    sa.Column('aprobado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_index(op.f('ix_solicitudes_id'), 'solicitudes', ['id'], unique=False)
    op.create_table('procesos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procesos_id'), 'procesos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procesos_id'), table_name='procesos')
    op.drop_table('procesos')
    op.drop_index(op.f('ix_solicitudes_id'), table_name='solicitudes')
    op.drop_table('solicitudes')
    # ### end Alembic commands ###
